name: Lint on Pull Request

on:
  pull_request:
    branches:
      - master  # Adjust to your default branch if different

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
